add SessionVOSer.java
fix java.io.NotSerializableException

issue :

java.io.NotSerializableException: oracle.jdbc.driver.OracleClobReader
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.common.ser.TheaterVOSer.export(TheaterVOSer.java:115)
	at com.common.ser.SerUtil.export(SerUtil.java:40)

root cause :
    java.io.Reader does not implement Interface Serializable

solution :
    modify data type of seat_model(TheaterVO) from Reader to String